# Generated by Django 2.2.7 on 2019-11-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('userInformation_id', models.AutoField(primary_key=True, serialize=False)),
                ('userfull_name', models.CharField(default='', max_length=100)),
                ('phone_no', models.CharField(default='', max_length=50)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('user_company', models.CharField(default='', max_length=50)),
                ('user_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.position')),
            ],
        ),
    ]
