# Generated by Django 2.2.7 on 2019-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_position_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_position',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='position',
        ),
    ]
