# Generated by Django 2.2.7 on 2019-12-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191206_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 1, 13, 16, 62254)),
        ),
    ]
